- name: composer
  src: geerlingguy.composer
  version: 1.7.0

- name: ntp
  src: geerlingguy.ntp
  version: 1.6.0

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: kamaln7.swapfile
  version: 4850d8a

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.3

- src: git+https://github.com/ItinerisLtd/trellis-backup-during-deploy.git
  version: 0.1.0 # Check for latest version!

- src: TypistTech.trellis-newrelic-php
  version: 0.4.0

- src: TypistTech.trellis-cloudflare-origin-ca
  version: 0.6.0
