- name: composer
  src: geerlingguy.composer
  version: 1.6.1

- name: ntp
  src: geerlingguy.ntp
  version: 1.5.2

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: kamaln7.swapfile
  version: 4850d8a

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.3

- src: TypistTech.trellis-newrelic-php
  version: 0.2.0

- src: TypistTech.trellis-cloudflare-origin-ca
  version: 0.5.0
